version: "3"

services:
  mysql-development:
    image: mysql:8.0.17
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./:/db
